export class Season {
  id: number = 0;
  cell111: string = '';
  cell112: string = '';
  cell113: string = '0';// 进口
  cell114: string = '0'; // 出口
  cell121: string = '';
  cell131: string = '';
  cell141: string = '';
  cell142: string = '';
  cell151: string = '';
  cell152: string = '';
  cell161: string = '';
  cell162: string = '';
  cell163: string = '';
  cell164: string = '';
  cell165: Date | string = new Date();

  // 原 report 属性
  cell11: string = '';
  cell12: string = '';
  cell13: string = '';
  cell14: string = '';
  cell15: string = '';
  cell21: string = '';
  cell22: string = '';
  cell23: string = '';
  cell24: string = '';
  cell25: string = '';
  cell31: string = '';
  cell32: string = '';
  cell33: string = '';
  cell34: string = '';
  cell35: string = '';
  cell41: string = '';
  cell42: string = '';
  cell43: string = '';
  cell44: string = '';
  cell45: string = '';
  cell51: string = '';
  cell52: string = '';
  cell53: string = '';
  cell54: string = '';
  cell55: string = '';
  cell61: string = '';
  cell62: string = '';
  cell63: string = '';
  cell64: string = '';
  cell65: string = '';
  cell71: string = '';
  cell72: string = '';
  cell73: string = '';
  cell74: string = '';
  cell75: string = '';
  cell81: string = '';
  cell82: string = '';
  cell83: string = '';
  cell84: string = '';
  cell85: string = '';
  cell91: string = '';

  cell92: string = '0';
  cell93: string = '0';
  cell94: string = '0';
  cell95: string = '0';

  cell101: string = '';
  cell102: string = '0';
  cell103: string = '0';
  cell104: string = '0';
  cell105: string = '0';

  o2oRadio: string = '2';// 1：是，2：否
  mobileRadio: string = '2';// 1：是，2：否
  companyName: string = '';
  year: string = '';
  industry: string = '';
  season: string = '1';
  userId: string = '';
  cityId: string = '';
  permission: string = '';
}
